/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/*/individual/*')
global class MoiRestIndividualController {
    global MoiRestIndividualController() {

    }
    @HttpPost
    global static FinServ.MoiRestResponse createIndividuals() {
        return null;
    }
    @HttpGet
    global static FinServ.MoiRestResponse getIndividuals() {
        return null;
    }
    @HttpPut
    global static FinServ.MoiRestResponse updateIndividuals() {
        return null;
    }
}
