/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ContactInteractionSchedulable implements System.Schedulable {
    global ContactInteractionSchedulable() {

    }
    global void execute(System.SchedulableContext sc) {

    }
    global static String getCronString(Datetime dt) {
        return null;
    }
}
