/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RunRBLBatchable implements Database.Batchable<SObject>, Database.Stateful {
    global RunRBLBatchable() {

    }
}
