/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class UpdateSubmissionP13ns implements Database.Batchable<SObject> {
    global UpdateSubmissionP13ns() {

    }
    global UpdateSubmissionP13ns(String email) {

    }
    global void execute(Database.BatchableContext BC, List<mcdm_15__SubmissionP13n__c> p13ns) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
}
