/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global interface BulkSendPlugin {
    Map<String,Map<String,String>> getBulkSendPluginData(List<mcdm_15.JourneyApproval> param0, Map<String,String> param1);
}
