/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class MarketingCloudDataSourceProvider extends DataSource.Provider {
    global MarketingCloudDataSourceProvider() {

    }
    global override List<DataSource.AuthenticationCapability> getAuthenticationCapabilities() {
        return null;
    }
    global override List<DataSource.Capability> getCapabilities() {
        return null;
    }
    global override DataSource.Connection getConnection(DataSource.ConnectionParams connectionParams) {
        return null;
    }
}
