/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class MarketingCloudDataSourceConnection extends DataSource.Connection {
    global MarketingCloudDataSourceConnection() {

    }
    global MarketingCloudDataSourceConnection(DataSource.ConnectionParams connectionParams) {

    }
    global override DataSource.TableResult query(DataSource.QueryContext context) {
        return null;
    }
    global override List<DataSource.TableResult> search(DataSource.SearchContext c) {
        return null;
    }
    global override List<DataSource.Table> sync() {
        return null;
    }
}
