/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class MarketingCloudOAuthProvider extends Auth.AuthProviderPluginClass {
    global String getCustomMetadataType() {
        return null;
    }
    global Auth.UserData getUserInfo(Map<String,String> authProviderConfiguration, Auth.AuthProviderTokenResponse response) {
        return null;
    }
    global Auth.AuthProviderTokenResponse handleCallback(Map<String,String> authProviderConfiguration, Auth.AuthProviderCallbackState state) {
        return null;
    }
    global System.PageReference initiate(Map<String,String> authProviderConfiguration, String stateToPropagate) {
        return null;
    }
    global override Auth.OAuthRefreshResult refresh(Map<String,String> authProviderConfiguration, String refreshToken) {
        return null;
    }
}
