/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class InvocableAutoSend {
    global InvocableAutoSend() {

    }
    @InvocableMethod(label='Send Auto Send')
    global static void sendAutoSend(List<mcdm_15__DM_Auto_Send__c> autoSends) {

    }
}
